// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKrCjlqUX7VJypAN9MknfiHrKlpi5V7ps',
    appId: '1:658177490660:web:67f83a9b763052f21c76f1',
    messagingSenderId: '658177490660',
    projectId: 'todo-route-a5f0a',
    authDomain: 'todo-route-a5f0a.firebaseapp.com',
    storageBucket: 'todo-route-a5f0a.appspot.com',
    measurementId: 'G-PF77QJZH1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6GliyzxCVGepJzaRQ6I0ubO72b9nHCY',
    appId: '1:658177490660:android:b3e3d8b7832c8ebb1c76f1',
    messagingSenderId: '658177490660',
    projectId: 'todo-route-a5f0a',
    storageBucket: 'todo-route-a5f0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDVNiXmUJDvNBCxU2f3hBNAU4nAuLnz4o',
    appId: '1:658177490660:ios:2e1451ece53ab3df1c76f1',
    messagingSenderId: '658177490660',
    projectId: 'todo-route-a5f0a',
    storageBucket: 'todo-route-a5f0a.appspot.com',
    iosClientId: '658177490660-30ina4v1j3l4783tms6k8ur4ajvp3iss.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppRoute',
  );
}
